GET http://raspberrypi.local:30578 HTTP/1.1

###


GET http://raspberrypi.local:30578/settings HTTP/1.1

###

POST http://192.168.0.177:30578/settings HTTP/1.1
content-type: application/json

{
    "themperatureSet": 26
}

###