GET http://192.168.0.177:3000 HTTP/1.1

###


GET http://192.168.0.177:3000/settings HTTP/1.1

###

POST http://192.168.0.177:3000/settings HTTP/1.1
content-type: application/json

{
    "themperatureSet": 26
}

###